apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-web
  namespace: kube-system
spec:
  secretName: tls-web
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - s-miras.com
