apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      enabled: true
      listeners:
        websecure:
          protocol: HTTPS
          port: 8443
          hostname: "s-miras.com"
          mode: Terminate
          namespacePolicy:
            from: All
          certificateRefs:
            - name: tls-web
              namespace: kube-system
              group: ""
              kind: Secret
