replicaCount: 1

image:
  repository: serikulymiras/web
  pullPolicy: IfNotPresent
  tag: 'v3'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

httpRoute:
  enabled: true
  gateway:
    name: traefik-gateway
    namespace: kube-system
  hostnames:
    - 's-miras.com'

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
